query TodoList($id: Float!) {
  todoList(id: $id) {
    id
    title
    todos {
      id
      text
      completed
    }
    template {
      id
      title
      user {
        id
        username
      }
    }
  }
}
